### ISSUE TITLE
This is my code LOL

### ISSUE THREAD

**Issue by BrailyGuzman** [yigitlegacy/NGL.link-Message-Spammer#1]
What's the point of copying and pasting my code, 
and making it look like you made it?

![image](https://user-images.githubusercontent.com/94770717/205393371-88a6d271-26b9-4dfd-89a2-f820cd5eb84f.png)

**Comment by yigitlegacy** [comment]
Wow man 😂 Didn't expect u would notice. Don't think like I tried to stole your code or something Im new to both Github and coding... so just trying new things out and trying to learn. I can delete this right now if u feel like it.

**Comment by yigitlegacy** [comment]
> What's the point of copying and pasting my code, 
> and making it look like you made it?
> 
> 
> ![image](https://user-images.githubusercontent.com/94770717/205393371-88a6d271-26b9-4dfd-89a2-f820cd5eb84f.png)
> 

Wow man 😂 Didn't expect u would notice. Don't think like I tried to stole your code or something, also I didnt meant to show it like mine. Im new to both Github and coding... so just trying new things out and trying to learn. I can delete this right now if u feel like it. Sorry!
